### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by 4xx22** [4xx22/TikToker#1]
- [ ] Manage when the bot Missing Permissions
- [ ] Dependencies cleanup
- [ ] Cleaner code
- [ ] ReadME
- [ ] Create option for removing the auto resolve on a guild
- [ ] Create option for faking the message of the author (with webhook)
